name: Release Package - Node

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release-node:
    permissions:
      contents: write
      packages: write
    uses: aws-geospatial/github-workflows-for-amazon-location/.github/workflows/node-release.yml@main
    with:
      node-version: "18.x"
      working-directory: "javascript"
      release-tag-prefix: "js-"
      release-title-prefix: "JS-"
    secrets:
      NPM_ORG_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}
